steps:
- name: node:14.20.0
  entrypoint: yarn
  args: ["install"]
- name: node:14.20.0
  entrypoint: yarn
  args: ["run", "create-env"]
- name: node:14.20.0
  entrypoint: yarn
  args: ["build"]
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "app.yaml", "build/app.yaml"]
- name: "gcr.io/cloud-builders/gcloud"
  dir: .
  args: ["app", "deploy"]
timeout: "1600s"
