steps:
- name: node:14.20.0
  entrypoint: yarn
  args: ["install"]
- name: node:14.20.0
  entrypoint: yarn
  args: ["run", "create-env"]
  env:
    - 'HOST=${_HOST}'
    - 'APP_KEY=${_APP_KEY}'
    - 'DB_CONNECTION=${_DB_CONNECTION}'
    - 'DRIVE_DISK=${_DRIVE_DISK}'
    - 'PG_DB_NAME=${_PG_DB_NAME}'
    - 'PG_HOST=${_PG_HOST}'
    - 'PG_PASSWORD=${_PG_PASSWORD}'
    - 'PG_PORT=${_PG_PORT}'
    - 'PG_USER=${_PG_USER}'
    - 'SESSION_DRIVER=${_SESSION_DRIVER}'
- name: node:14.20.0
  entrypoint: yarn
  args: ["build"]
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "app.yaml", "build/app.yaml"]
- name: "gcr.io/cloud-builders/gcloud"
  dir: .
  args: ["app", "deploy"]
timeout: "1600s"
